name: tmp import updater header
on:
  push:
    paths:
      - '.github/workflows/tmp-import-updater-header.yml'
permissions:
  contents: write
jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p plugin-update/files/assets
          curl -L 'https://sdmntprdenmarkeast.oaiusercontent.com/files/00000000-d118-8210-9917-f350f284112f/raw?se=2026-09-12T19%3A30%3A10Z&sp=r&sv=2026-02-06&sr=b&scid=ed6b705b-4379-51de-9f20-ea26d7f91c20&skoid=8981e47a-681f-4a6a-b86c-73d6347614b7&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2026-09-12T16%3A20%3A06Z&ske=2026-09-13T16%3A20%3A06Z&sks=b&skv=2026-02-06&sig=N2m3%2Be2aKCzeOZhrURe%2BQVyLNhjpz/iyQh/0Hso7x%2BY%3D' -o /tmp/headers.zip
          unzip -o /tmp/headers.zip -d /tmp/headers
          cp /tmp/headers/updater_header_fhd.jpg plugin-update/files/assets/
          cp /tmp/headers/updater_header_hd.jpg plugin-update/files/assets/
          sha256sum plugin-update/files/assets/updater_header_*.jpg
          git config user.name Warder
          git config user.email 44697180+PiconHub-Warder@users.noreply.github.com
          git add plugin-update/files/assets/updater_header_*.jpg
          git commit -m 'Add clean updater header assets'
          git push
